### ISSUE TITLE
[Error] first path segment in URL cannot contain colon

### ISSUE THREAD

**Issue by roomit-xyz** [strangelove-ventures/horcrux#175] opened 2023-07-18 14:17 UTC
Hallo Team,

Could you help me, when I try this command in 3 node horcrux I have, we have got this error :
 
```
$ horcrux elect 2

Broadcasting to address: multi:///192.168.66.3:16701,192.168.66.4:16701,192.168.66.5:16701
Error: dialing failed: failed to build resolver: parse "192.168.66.3:16701": first path segment in URL cannot contain colon
```

Port already opened and I can telnet each other horcrux node.

Best Regards
RoomIT

**Comment by agouin** [comment] 2023-07-18 14:26
Duplicate of #166

Thank you for your issue! This will be resolved in v3.1.0, which we plan to release this week.

**Closed by agouin** 2023-07-18 14:26 UTC
