### ISSUE TITLE
Cannot Elect node using CLI

### ISSUE THREAD

**Issue by Quilamir** [strangelove-ventures/horcrux#172] opened 2023-07-14 20:00 UTC
in version 3.0.0 it seems its not possible to elect a node using the cli.

when running horcrux elect an error is returned:

Broadcasting to address: multi:///10.138.0.19:2222,10.128.0.44:2222,10.150.0.3:2222
Error: dialing failed: failed to build resolver: parse "10.138.0.19:2222": first path segment in URL cannot contain colon

same thing happens when running the election with a specific node id

**Comment by agouin** [comment] 2023-07-14 20:11
Duplicate of #166

Thank you for your issue! This will be resolved in v3.1.0, which we plan to release next week.

**Closed by agouin** 2023-07-14 20:11 UTC
